language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - S3_KEY="AKIAIVX3QG6GGNREGYMA" S3_BUCKET="app-travis-filer-s3"
  - secure: LrGedROKtVMYlHoXdsrsLFr1W4eES7VXhih6Ze6tq6D9VpPqqaPt17iSSIKIdhh6BN8LA89AGKQxIA63GX7aAp1J0Mz8VMNxlSj4tjQ8UcsJpunw/yDb77ocFlfER1spepnFDMIEz9QcfU9M8jSG8GxTtD2yeMrw2vSxSXv69mY=
